sample_arr = [];
sample_arr['Phrases'] = [['どうも・ありがとうございました','Thank you very much'],
['いただきます','said before eating a meal'],
['いらっしゃい・ませ','Welcome to a store'],
['では おげんきで','when parting Stay healthy'],
['おねがいします','Please do for me'],
['おはようございます','Good morning very polite'],
['おやすみなさい','Good night very polite'],
['ごちそうさま・でした','Thank you for the meal very polite'],
['こちらこそ','It is I who should say so'],
['ごめんください','May I come in'],
['ごめんなさい','Sorry'],
['こんにちは','Hello good day'],
['こんばんは','Good Evening'],
['さよなら｜さようなら','Farewell'],
['しつれいしました','Sorry for my rudeness'],
['しつれいします','Sorry for my rudeness'],
['すみません','Sorry'],
['では、また','Ok, I\'ll see you later'],
['いいえ どういたしまして','Not at all you\'re welcome'],
['はじめまして','Nice to meet you'],
['どうぞ よろしく','Pleased to meet you'],
['やあ','Hi'],
['おはようございます','Good morning'],
['こんばんは','Good evening'],
['ようこそいらっしゃいました','Welcome to greet someone'],
['お元気ですか？','How are you'],
['わたしは元気ですありがとう','I\'m fine, thanks'],
['あなたは？','And you'],
['元気です まあまあです','Good So-So'],
['ありがとう','Thank you very much'],
['どういたしまして','You\'re welcome for "thank you"'],
['さみしかったです','I missed you so much'],
['最近どうですか？','What\'s new'],
['変わりないです','Nothing much'],
['おやすみなさい','Good night'],
['またあとで会いましょう','See you later'],
['さようなら','Good bye'],
['迷ってしまいました','I\'m lost'],
['お手伝いしましょうか？','Can I help you'],
['手伝ってくれますか？','Can you help me'],
['トイレ薬局 はどこですか？','Where is the bathroom pharmacy'],
['まっすぐ行ってくださいそして、 左／右にまがってください','Go straight then turn left right'],
['Johnを探しています','I\'m looking for john'],
['ちょっと待ってください','One moment please'],
['ちょっと待ってください','Hold on please phone'],
['これはいくらですか？','How much is this'],
['すみません','Excuse me'],
['私といっしょに来てください','Come with me'],
['あなたは（英語／日本語）を話しますか？','Do you speak English Japanese'],
['少しだけ','Just a little'],
['名前は何ですか？','What\'s your name'],
['私の名前は・・・','My name is '],
['・・・さん','Mr Mrs… Miss…'],
['はじめまして／お会いできてうれしいです','Nice to meet you'],
['あなたはとてもしんせつです','You\'re very kind'],
['どこの出身ですか？','Where are you from'],
['アメリカ／日本からです','I\'m from the US Japan'],
['私はアメリカ人です','I\'m American'],
['どこに住んでいますか？','Where do you live'],
['私はアメリカ／日本に住んでいます','I live in the US Japan'],
['ここは好きになりましたか？','Did you like it here'],
['日本は素晴らしい国です','Japan is a wonderful country'],
['お仕事は何ですか？','What do you do for a living'],
['ほんやく／会社員として働いています','I work as a translator businessman'],
['私は日本語が好きです','I like Japanese'],
['私は日本語を一ヶ月習っています','I\'ve been learning Japanese for one month'],
['それはいいですね','Oh That\'s good'],
['年はいくつですか？','How old are you'],
['私は（２０，３０）才です','I\'m twenty, thirty years old'],
['行かなくてはなりません','I have to go'],
['すぐ戻ります','I will be right back'],
['がんばってね','Good luck'],
['誕生日おめでとうございます','Happy birthday'],
['あけましておめでとうございます','Happy new year'],
['メリークリスマス','Merry Christmas'],
['おめでとう','Congratulations'],
[' を楽しんでください','Enjoy for meals'],
['いつか日本を訪れたい','I\'d like to visit Japan one day'],
['Johnによろしくと伝えてください','Say hi to John for me'],
['お大事に','Bless you when sneezing'],
['おやすみなさい','Good night and sweet dreams'],
['ごめんなさい','Sorry for a mistake'],
['大丈夫です','No Problem'],
['もういちど言ってくれますか？','Can You Say It Again'],
['ゆっくりしゃべってくれますか？','Can You Speak Slowly'],
['書いてください','Write It Down Please'],
['わかりません','I Do not Understand'],
['知りません','I Do not Know'],
['わかりません','I Have No Idea'],
['あれは日本語で何といいますか？','What\'s That Called In Japanese'],
['Gato は英語でどういう意味ですか？','What Does "gato" Mean In English'],
['“Please” は日本語で何と言いますか？','How Do You Say "Please" In Japanese'],
['これは何ですか？','What Is This'],
['私の日本語はへたです','My Japanese is bad'],
['日本語を練習する必要があります','I need to practice my Japanese'],
['ご心配なく','Do not worry'],
['よい','Good'],
['悪い','Bad'],
['まあまあ','So-So'],
['大きい','Big'],
['小さい','Small'],
['今日／今','Today Now'],
['明日／昨日','Tomorrow Yesterday'],
['はい／いいえ','Yes No'],
['はい、どうぞ','Here you go when giving something'],
['好きですか？','Do you like it'],
['ほんとに好きです','I really like it'],
['おなかが空きました／のどがかわきました','I\'m hungry thirsty'],
['朝に／夕方に／夜に','In The Morning Evening At Night'],
['これ／あれ ここ／あそこ','This That HereThere'],
['私／あなた　彼／彼女','Me You Him Her'],
['ほんと','Really'],
['見て','Look'],
['急いで','Hurry up'],
['何？どこ？','What Where'],
['何時ですか？','What time is it'],
['十時です午後７時３０分です','It\'s 10 o\'clock 07:30pm'],
['これをください','Give me this'],
['大好きですあなたを愛しています','I love you'],
['調子が悪いです','I feel sick'],
['病院に行きたい','I need a doctor'],
['いち、に、さん','One, Two, Three'],
['よん、ご、ろく','Four, Five, Six'],
['なな（ひち）、はち、きゅう、じゅう','Seven, Eight, Nine, Ten']
];

sample_arr['Count'] = [
    ['一','1'],
    ['二','2'],
    ['三','3'],
    ['四','4'],
    ['五','5'],
    ['六','6'],
    ['七','7'],
    ['八','8'],
    ['九','9'],
    ['十','10'],
    ['百','100'],
    ['千','1,000'],
    ['万','10,000'],
    ['十万','100,000'],
    ['百万','1,000,000'],
    ['千万','10,000,000'],
    ['一億','100,000,000'],
    ['十億','1,000,000,000'],
    ['一兆','1,000,000,000,000'],
    ['いち','1'],
    ['に','2'],
    ['さん','3'],
    ['よん','4'],
    ['ご','5'],
    ['ろく','6'],
    ['なな','7'],
    ['はち','8'],
    ['きゅう','9'],
    ['じゅう','10'],
    ['ひゃく','100'],
    ['せん','1,000'],
    ['まん','10,000'],
    ['じゅうまん','100,000'],
    ['ひゃくまん','1,000,000'],
    ['せんまん','10,000,000'],
    ['いちおく','100,000,000'],
    ['じゅうおく','1,000,000,000'],
];

sample_arr['Dates'] = [
    ['一月','January'],
    ['二月','February'],
    ['三月','March'],
    ['四月','April'],
    ['五月','May'],
    ['六月','June'],
    ['七月','July'],
    ['八月','August'],
    ['九月','September'],
    ['十月','October'],
    ['十一月','November'],
    ['十二月','December'],
    ['日曜日','Sunday'],
    ['月曜日','Monday'],
    ['火曜日','Tuesday'],
    ['水曜日','Wednesday'],
    ['木曜日','Thrusday'],
    ['金曜日','Friday'],
    ['土曜日','Saturday'],
    ['四季','Four seasons'],
    ['春','Spring'],
    ['夏','Summer'],
    ['秋','Autumn'],
    ['冬','Winter']
];

sample_arr['Body'] = [
    ['体','body'],
    ['頭','head'],
    ['髪','hair'],
    ['顔','face'],
    ['額','forehead'],
    ['目','eye'],
    ['眉','eyebrow'],
    ['まぶた','eyelid'],
    ['まつげ','eyelash'],
    ['鼻','nose'],
    ['耳','ear'],
    ['口','mouth'],
    ['唇','lip'],
    ['歯','teeth'],
    ['舌','tongue'],
    ['のど','throat'],
    ['あご','jaw'],
    ['首','neck'],
    ['肩','shoulder'],
    ['腕','arm'],
    ['ひじ','elbow'],
    ['手','hand'],
    ['指','finger'],
    ['爪','nail'],
    ['胸','chest'],
    ['背中','back'],
    ['おなか','stomach'],
    ['ひざ','knee'],
    ['足首','ankle'],
    ['かかと','heel'],
    ['つまさき','toe']
];
	
sample_arr['Fruit'] = [
    ['果物','Fruit(s)'],
    ['柿','Persimmon'],
    ['メロン','Melon'],
    ['みかん','Orange*'],
    ['桃','Peach'],
    ['なし','Pear'],
    ['梅','Plum'],
    ['バナナ','Banana'],
    ['メロン','Melon'],
    ['オレンジ','Orange'],
    ['レモン','Lemon'],
    ['杏','Apricot'],
    ['ぶどう','Grapes'],
    ['いちご','Strawberry'],
    ['いちじく','Fig'],
    ['りんご','Apple'],
    ['さくらんぼ','Cherry'],
    ['スイカ','Watermelon']
];	